name: mime_health
description: Production-ready Mime Health Flutter application with Clean Architecture.
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management & DI
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

  # Networking
  dio: ^5.8.0+1
  talker_dio_logger: ^4.7.2
  talker_flutter: ^4.7.2

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # Connectivity & device
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.4.0

  # Routing
  go_router: ^15.1.2

  # Utilities
  equatable: ^2.0.7
  uuid: ^4.5.1
  collection: ^1.19.1
  intl: ^0.20.3
  image_picker: ^1.2.3
  file_picker: ^11.0.2
  flutter_svg: ^2.1.0
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  google_sign_in: ^7.2.0
  record: ^7.1.1
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
