import 'l10n_keys.dart';

/// Built-in fallback strings used before / if the language API fails.
///
/// Keys match the backend `data.items` map from `/translations/locales/{locale}`.
class FallbackStrings {
  FallbackStrings._();

  static const Map<String, String> en = {
    L10nKeys.loginTitle: 'Login with phone number',
    L10nKeys.nameLabel: 'Your name',
    L10nKeys.otpLabel: 'Enter 4-digit code',
    L10nKeys.phoneLabel: 'Phone number',
    L10nKeys.resendOtp: 'Resend OTP',
    L10nKeys.sendOtp: 'Send OTP',
    L10nKeys.verifyOtp: 'Verify',
    L10nKeys.genericError: 'Something went wrong. Please try again.',
    L10nKeys.networkError: 'Check your internet connection.',
    L10nKeys.homeStartScan: 'Start scan to create a profile',
    L10nKeys.homeWelcome: 'Welcome',
    L10nKeys.homeCreateProfile: 'Create New Profile',
    L10nKeys.homeDateOfBirth: 'DATE OF BIRTH',
    L10nKeys.homeMonth: 'Month',
    L10nKeys.homeDay: 'Day',
    L10nKeys.homeYear: 'Year',
    L10nKeys.homeGender: 'GENDER',
    L10nKeys.homeMale: 'Male',
    L10nKeys.homeFemale: 'Female',
    L10nKeys.homeLifestyle: 'LIFESTYLE',
    L10nKeys.homeActive: 'Active',
    L10nKeys.homeModerate: 'Moderate',
    L10nKeys.homeInactive: 'Inactive',
    L10nKeys.homeSelf: 'Self',
    L10nKeys.homeFamily: 'Family',
    L10nKeys.homeOther: 'Other',
    L10nKeys.homeDisplayName: 'Display name',
    L10nKeys.homeWellBeingTitle: 'WELL-BEING AND LIFESTYLE INDICATORS',
    L10nKeys.homeSmoker: 'Smoker',
    L10nKeys.homeDiabetes: 'Diabetes',
    L10nKeys.homeHypertension: 'Hypertension',
    L10nKeys.homeHighGlucose: 'High Glucose Levels',
    L10nKeys.homeHubTitle: 'MiMe Health',
    L10nKeys.homeHubHeadline: 'Your AI Health\nCompanion',
    L10nKeys.homeHubSubtitle:
        'Advanced AI Technology analyzes your health and helps you live better every day',
    L10nKeys.homeNavHome: 'Home',
    L10nKeys.homeNavHealthHub: 'Health Hub',
    L10nKeys.healthHubNoScan:
        'No scan results yet. Complete a face scan to see your health dashboard here.',
    L10nKeys.homeNavFaceScan: 'Face Scan',
    L10nKeys.homeNavTrends: 'Trends',
    L10nKeys.homeNavProfile: 'Profile',
    L10nKeys.feedbackTooltip: 'Send feedback',
    L10nKeys.feedbackTitle: 'Share your feedback',
    L10nKeys.feedbackMessage: 'Message',
    L10nKeys.feedbackRecordVoice: 'Record voice',
    L10nKeys.feedbackStopRecording: 'Stop recording',
    L10nKeys.feedbackAudioReady: 'Voice recording ready',
    L10nKeys.feedbackRemoveAudio: 'Remove recording',
    L10nKeys.feedbackSend: 'Send',
    L10nKeys.feedbackCancel: 'Cancel',
    L10nKeys.feedbackRequired: 'Please enter a message or record your voice.',
    L10nKeys.feedbackMicrophonePermission:
        'Microphone permission is required to record voice feedback.',
    L10nKeys.profileDetailsTitle: 'Profile',
    L10nKeys.profileEdit: 'Edit profile',
    L10nKeys.profileAddPhoto: 'Add photo',
    L10nKeys.profileUpdatePhoto: 'Update photo',
    L10nKeys.profileBloodGroup: 'Blood group',
    L10nKeys.profileHeight: 'Height',
    L10nKeys.profileHeightFeet: 'Height (ft)',
    L10nKeys.profileHeightInches: 'Height (in)',
    L10nKeys.profileWeight: 'Weight',
    L10nKeys.profileWeightKg: 'Weight (kg)',
    L10nKeys.profileAge: 'Age',
    L10nKeys.profilePhone: 'Phone number',
    L10nKeys.profileEmail: 'Email address',
    L10nKeys.profileStatus: 'Status',
    L10nKeys.profileKind: 'Profile type',
    L10nKeys.profileYes: 'Yes',
    L10nKeys.profileNo: 'No',
    L10nKeys.profileNotSet: 'Not set',
    L10nKeys.profilePhotoSoon: 'Profile photo update will be available soon.',
    L10nKeys.profilePhotoChoose: 'Choose photo',
    L10nKeys.profilePhotoUploadSuccess: 'Profile photo updated.',
    L10nKeys.mediaCamera: 'Camera',
    L10nKeys.mediaGallery: 'Gallery',
    L10nKeys.mediaFiles: 'Files',
    L10nKeys.mediaCancel: 'Cancel',
    L10nKeys.mediaChooseSource: 'Choose source',
    L10nKeys.faceScanTitle: 'Face scan',
    L10nKeys.faceScanIntro:
        'We use your front camera for about 20 seconds to measure vitals. Data is processed securely via IntelliProve.',
    L10nKeys.faceScanTipLightingTitle: 'Good lighting',
    L10nKeys.faceScanTipLightingBody:
        'Face a window or lamp — avoid strong backlight.',
    L10nKeys.faceScanTipHoldStillTitle: 'Hold still',
    L10nKeys.faceScanTipHoldStillBody:
        'Keep your face centred and stay on this screen.',
    L10nKeys.faceScanTipScreenOnTitle: 'Keep screen on',
    L10nKeys.faceScanTipScreenOnBody:
        'Do not switch apps until the scan finishes.',
    L10nKeys.faceScanConsent:
        'I agree to the face scan and understand this is not a medical diagnosis.',
    L10nKeys.faceScanStart: 'Start MiME face scan',
    L10nKeys.questionnaireTitle: 'Health Questionnaire',
    L10nKeys.questionnaireProgress: 'Question {current} of {total}',
    L10nKeys.questionnaireSkip: 'Skip for now',
    L10nKeys.faceScanChoosePlan: 'Choose a plan',
    L10nKeys.faceScanUrlFailedMessage: 'Unable to provide the service at this moment. Please try again later.',
    L10nKeys.faceScanPlanRequired:
        'Select a subscription plan before starting a face scan.',
    L10nKeys.faceScanResultsLoadingTitle: 'Loading your results...',
    L10nKeys.faceScanResultsLoadingSubtitle: 'Please wait a moment.',
    L10nKeys.healthDashboardTitle: 'Health Dashboard',
    L10nKeys.healthDashboardOverallScore: 'Overall health score',
    L10nKeys.healthDashboardBiomarkers: 'Biomarkers',
    L10nKeys.healthDashboardHeartRate: 'Heart Rate',
    L10nKeys.healthDashboardBloodPressure: 'Blood Pressure',
    L10nKeys.healthDashboardRespRate: 'Resp. Rate',
    L10nKeys.healthDashboardSpo2: 'SpO2',
    L10nKeys.healthDashboardHrv: 'Heart Rate Variability',
    L10nKeys.healthDashboardMetrics: 'Metrics',
    L10nKeys.healthDashboardUpgradeTitle: 'Unlock Your Full Health Potential',
    L10nKeys.healthDashboardUpgradeBody:
        'Gain access to exclusive insights and predictive analytics',
    L10nKeys.healthDashboardUpgradeCta: 'Upgrade now',
    L10nKeys.healthDashboardConsult: 'Consult Doctors',
    L10nKeys.healthDashboardLabTest: 'Book Lab Test',
    L10nKeys.healthDashboardMedicine: 'Order Medicine',
    L10nKeys.subscriptionTitle: 'Choose your plan',
    L10nKeys.subscriptionSubtitle:
        'Pick a plan to unlock face scans and health insights.',
    L10nKeys.subscriptionMonthly: 'Monthly',
    L10nKeys.subscriptionAnnual: 'Annual',
    L10nKeys.subscriptionContinue: 'Continue with this plan',
    L10nKeys.subscriptionUnlimited: 'Unlimited',
    L10nKeys.subscriptionProfiles: 'Up to {count} profiles',
    L10nKeys.subscriptionScans: '{count} scans / month',
    L10nKeys.subscriptionTrial: '{days}-day free trial',
    L10nKeys.subscriptionBiomarkers: '{count} biomarkers',
    L10nKeys.subscriptionDevices: '{count} devices',
    L10nKeys.subscriptionPayNow: 'Pay Now',
    L10nKeys.subscriptionHealthCheckup: '{name} Health Checkup',
    L10nKeys.language: 'Language',
    L10nKeys.languageBn: 'বাংলা',
    L10nKeys.languageEn: 'English',
    // Local-only
    L10nKeys.appName: 'Mime Health',
    L10nKeys.changePhone: 'Change number',
    L10nKeys.otpSentTo: 'OTP sent to {phone}',
    L10nKeys.resendOtpIn: 'Resend OTP in {seconds}s',
    L10nKeys.logout: 'Logout',
    L10nKeys.logoutConfirmTitle: 'Sign out?',
    L10nKeys.logoutConfirmMessage: 'Are you sure you want to sign out?',
    L10nKeys.retry: 'Retry',
    L10nKeys.splashLoading: 'Preparing your experience...',
    L10nKeys.notFoundTitle: 'Page not found',
    L10nKeys.notFoundMessage: 'The page you are looking for does not exist.',
    L10nKeys.goHome: 'Go Home',
    L10nKeys.homeTitle: 'Home',
    L10nKeys.signInAsGuest: 'Sign in as Guest',
    L10nKeys.signIn: 'Sign in',
    L10nKeys.orContinueWith: 'Or continue with',
    L10nKeys.continueWithGoogle: 'Continue with Google',
  };

  static const Map<String, String> bn = {
    L10nKeys.loginTitle: 'ফোন নম্বর দিয়ে লগইন করুন',
    L10nKeys.nameLabel: 'আপনার নাম',
    L10nKeys.otpLabel: '৪ অঙ্কের কোড লিখুন',
    L10nKeys.phoneLabel: 'ফোন নম্বর',
    L10nKeys.resendOtp: 'আবার OTP পাঠান',
    L10nKeys.sendOtp: 'OTP পাঠান',
    L10nKeys.verifyOtp: 'যাচাই করুন',
    L10nKeys.genericError: 'কিছু ভুল হয়েছে। আবার চেষ্টা করুন।',
    L10nKeys.networkError: 'ইন্টারনেট সংযোগ পরীক্ষা করুন।',
    L10nKeys.homeStartScan: 'প্রোফাইল তৈরি করতে স্ক্যান শুরু করুন',
    L10nKeys.homeWelcome: 'স্বাগতম',
    L10nKeys.homeCreateProfile: 'নতুন প্রোফাইল তৈরি করুন',
    L10nKeys.homeDateOfBirth: 'জন্ম তারিখ',
    L10nKeys.homeMonth: 'মাস',
    L10nKeys.homeDay: 'দিন',
    L10nKeys.homeYear: 'বছর',
    L10nKeys.homeGender: 'লিঙ্গ',
    L10nKeys.homeMale: 'পুরুষ',
    L10nKeys.homeFemale: 'নারী',
    L10nKeys.homeLifestyle: 'জীবনধারা',
    L10nKeys.homeActive: 'সক্রিয়',
    L10nKeys.homeModerate: 'মাঝারি',
    L10nKeys.homeInactive: 'নিষ্ক্রিয়',
    L10nKeys.homeSelf: 'নিজের',
    L10nKeys.homeFamily: 'পরিবার',
    L10nKeys.homeOther: 'অন্যান্য',
    L10nKeys.homeDisplayName: 'প্রদর্শন নাম',
    L10nKeys.homeWellBeingTitle: 'সুস্থতা ও জীবনধারা সূচক',
    L10nKeys.homeSmoker: 'ধূমপায়ী',
    L10nKeys.homeDiabetes: 'ডায়াবেটিস',
    L10nKeys.homeHypertension: 'উচ্চ রক্তচাপ',
    L10nKeys.homeHighGlucose: 'উচ্চ গ্লুকোজের মাত্রা',
    L10nKeys.homeHubTitle: 'মাইম হেলথ',
    L10nKeys.homeHubHeadline: 'আপনার AI স্বাস্থ্য\nসঙ্গী',
    L10nKeys.homeHubSubtitle:
        'উন্নত AI প্রযুক্তি আপনার স্বাস্থ্য বিশ্লেষণ করে এবং প্রতিদিন আরও ভালোভাবে বাঁচতে সাহায্য করে',
    L10nKeys.homeNavHome: 'হোম',
    L10nKeys.homeNavHealthHub: 'হেলথ হাব',
    L10nKeys.healthHubNoScan:
        'এখনো কোনো স্ক্যান ফলাফল নেই। আপনার হেলথ ড্যাশবোর্ড দেখতে একটি ফেস স্ক্যান সম্পন্ন করুন।',
    L10nKeys.homeNavFaceScan: 'ফেস স্ক্যান',
    L10nKeys.homeNavTrends: 'ট্রেন্ডস',
    L10nKeys.homeNavProfile: 'প্রোফাইল',
    L10nKeys.feedbackTooltip: 'মতামত পাঠান',
    L10nKeys.feedbackTitle: 'আপনার মতামত জানান',
    L10nKeys.feedbackMessage: 'বার্তা',
    L10nKeys.feedbackRecordVoice: 'ভয়েস রেকর্ড করুন',
    L10nKeys.feedbackStopRecording: 'রেকর্ডিং বন্ধ করুন',
    L10nKeys.feedbackAudioReady: 'ভয়েস রেকর্ডিং প্রস্তুত',
    L10nKeys.feedbackRemoveAudio: 'রেকর্ডিং সরান',
    L10nKeys.feedbackSend: 'পাঠান',
    L10nKeys.feedbackCancel: 'বাতিল',
    L10nKeys.feedbackRequired:
        'একটি বার্তা লিখুন অথবা আপনার ভয়েস রেকর্ড করুন।',
    L10nKeys.feedbackMicrophonePermission:
        'ভয়েস মতামত রেকর্ড করতে মাইক্রোফোনের অনুমতি প্রয়োজন।',
    L10nKeys.profileDetailsTitle: 'প্রোফাইল',
    L10nKeys.profileEdit: 'প্রোফাইল সম্পাদনা',
    L10nKeys.profileAddPhoto: 'ছবি যোগ করুন',
    L10nKeys.profileUpdatePhoto: 'ছবি আপডেট করুন',
    L10nKeys.profileBloodGroup: 'রক্তের গ্রুপ',
    L10nKeys.profileHeight: 'উচ্চতা',
    L10nKeys.profileHeightFeet: 'উচ্চতা (ফুট)',
    L10nKeys.profileHeightInches: 'উচ্চতা (ইঞ্চি)',
    L10nKeys.profileWeight: 'ওজন',
    L10nKeys.profileWeightKg: 'ওজন (কেজি)',
    L10nKeys.profileAge: 'বয়স',
    L10nKeys.profilePhone: 'ফোন নম্বর',
    L10nKeys.profileEmail: 'ইমেইল ঠিকানা',
    L10nKeys.profileStatus: 'স্ট্যাটাস',
    L10nKeys.profileKind: 'প্রোফাইল ধরন',
    L10nKeys.profileYes: 'হ্যাঁ',
    L10nKeys.profileNo: 'না',
    L10nKeys.profileNotSet: 'সেট করা নেই',
    L10nKeys.profilePhotoSoon: 'প্রোফাইল ছবি আপডেট শীঘ্রই আসছে।',
    L10nKeys.profilePhotoChoose: 'ছবি বেছে নিন',
    L10nKeys.profilePhotoUploadSuccess: 'প্রোফাইল ছবি আপডেট হয়েছে।',
    L10nKeys.mediaCamera: 'ক্যামেরা',
    L10nKeys.mediaGallery: 'গ্যালারি',
    L10nKeys.mediaFiles: 'ফাইল',
    L10nKeys.mediaCancel: 'বাতিল',
    L10nKeys.mediaChooseSource: 'উৎস বেছে নিন',
    L10nKeys.faceScanTitle: 'ফেস স্ক্যান',
    L10nKeys.faceScanIntro:
        'আমরা প্রায় ২০ সেকেন্ডের জন্য আপনার সামনের ক্যামেরা ব্যবহার করে ভাইটালস পরিমাপ করি। ডেটা IntelliProve এর মাধ্যমে নিরাপদে প্রক্রিয়া করা হয়।',
    L10nKeys.faceScanTipLightingTitle: 'ভালো আলো',
    L10nKeys.faceScanTipLightingBody:
        'জানালা বা ল্যাম্পের দিকে মুখ করুন — তীব্র ব্যাকলাইট এড়িয়ে চলুন।',
    L10nKeys.faceScanTipHoldStillTitle: 'স্থির থাকুন',
    L10nKeys.faceScanTipHoldStillBody:
        'মুখ মাঝখানে রাখুন এবং এই স্ক্রিনেই থাকুন।',
    L10nKeys.faceScanTipScreenOnTitle: 'স্ক্রিন চালু রাখুন',
    L10nKeys.faceScanTipScreenOnBody:
        'স্ক্যান শেষ না হওয়া পর্যন্ত অন্য অ্যাপে যাবেন না।',
    L10nKeys.faceScanConsent:
        'আমি ফেস স্ক্যানে সম্মতি দিচ্ছি এবং বুঝতে পারছি এটি কোনো চিকিৎসা নির্ণয় নয়।',
    L10nKeys.faceScanStart: 'MiME ফেস স্ক্যান শুরু করুন',
    L10nKeys.questionnaireTitle: 'স্বাস্থ্য প্রশ্নমালা',
    L10nKeys.questionnaireProgress: 'প্রশ্ন {current} / {total}',
    L10nKeys.questionnaireSkip: 'এখনকার জন্য এড়িয়ে যান',
    L10nKeys.faceScanChoosePlan: 'প্ল্যান বেছে নিন',
    L10nKeys.faceScanUrlFailedMessage: 'এই মুহূর্তে সেবাটি প্রদান করা সম্ভব হচ্ছে না। অনুগ্রহ করে কিছুক্ষণ পর আবার চেষ্টা করুন।',
    L10nKeys.faceScanPlanRequired:
        'ফেস স্ক্যান শুরু করার আগে একটি সাবস্ক্রিপশন প্ল্যান বেছে নিন।',
    L10nKeys.faceScanResultsLoadingTitle: 'আপনার ফলাফল লোড হচ্ছে...',
    L10nKeys.faceScanResultsLoadingSubtitle: 'অনুগ্রহ করে একটু অপেক্ষা করুন।',
    L10nKeys.healthDashboardTitle: 'হেলথ ড্যাশবোর্ড',
    L10nKeys.healthDashboardOverallScore: 'সামগ্রিক স্বাস্থ্য স্কোর',
    L10nKeys.healthDashboardBiomarkers: 'বায়োমার্কার',
    L10nKeys.healthDashboardHeartRate: 'হার্ট রেট',
    L10nKeys.healthDashboardBloodPressure: 'ব্লাড প্রেসার',
    L10nKeys.healthDashboardRespRate: 'শ্বাসহার',
    L10nKeys.healthDashboardSpo2: 'SpO2',
    L10nKeys.healthDashboardHrv: 'হার্ট রেট ভ্যারিয়েবিলিটি',
    L10nKeys.healthDashboardMetrics: 'মেট্রিক্স',
    L10nKeys.healthDashboardUpgradeTitle:
        'সম্পূর্ণ স্বাস্থ্য সম্ভাবনা আনলক করুন',
    L10nKeys.healthDashboardUpgradeBody:
        'এক্সক্লুসিভ ইনসাইট ও প্রেডিকটিভ অ্যানালিটিক্স পান',
    L10nKeys.healthDashboardUpgradeCta: 'এখনই আপগ্রেড করুন',
    L10nKeys.healthDashboardConsult: 'ডাক্তারের পরামর্শ',
    L10nKeys.healthDashboardLabTest: 'ল্যাব টেস্ট বুক করুন',
    L10nKeys.healthDashboardMedicine: 'ওষুধ অর্ডার করুন',
    L10nKeys.subscriptionTitle: 'আপনার প্ল্যান বেছে নিন',
    L10nKeys.subscriptionSubtitle:
        'ফেস স্ক্যান ও স্বাস্থ্য অন্তর্দৃষ্টি আনলক করতে একটি প্ল্যান বেছে নিন।',
    L10nKeys.subscriptionMonthly: 'মাসিক',
    L10nKeys.subscriptionAnnual: 'বার্ষিক',
    L10nKeys.subscriptionContinue: 'এই প্ল্যান দিয়ে এগোন',
    L10nKeys.subscriptionUnlimited: 'সীমাহীন',
    L10nKeys.subscriptionProfiles: 'সর্বোচ্চ {count}টি প্রোফাইল',
    L10nKeys.subscriptionScans: 'মাসে {count}টি স্ক্যান',
    L10nKeys.subscriptionTrial: '{days} দিনের ফ্রি ট্রায়াল',
    L10nKeys.subscriptionBiomarkers: '{count}টি বায়োমার্কার',
    L10nKeys.subscriptionDevices: '{count}টি ডিভাইস',
    L10nKeys.subscriptionPayNow: 'এখনই পেমেন্ট করুন',
    L10nKeys.subscriptionHealthCheckup: '{name} স্বাস্থ্য পরীক্ষা',
    L10nKeys.language: 'ভাষা',
    L10nKeys.languageBn: 'বাংলা',
    L10nKeys.languageEn: 'English',
    // Local-only
    L10nKeys.appName: 'মাইম হেলথ',
    L10nKeys.changePhone: 'নম্বর পরিবর্তন করুন',
    L10nKeys.otpSentTo: '{phone} এ OTP পাঠানো হয়েছে',
    L10nKeys.resendOtpIn: '{seconds} সে. পর আবার পাঠান',
    L10nKeys.logout: 'লগআউট',
    L10nKeys.logoutConfirmTitle: 'সাইন আউট করবেন?',
    L10nKeys.logoutConfirmMessage: 'আপনি কি নিশ্চিত যে সাইন আউট করতে চান?',
    L10nKeys.retry: 'আবার চেষ্টা করুন',
    L10nKeys.splashLoading: 'আপনার অভিজ্ঞতা প্রস্তুত করা হচ্ছে...',
    L10nKeys.notFoundTitle: 'পেজ পাওয়া যায়নি',
    L10nKeys.notFoundMessage: 'আপনি যে পেজটি খুঁজছেন তা নেই।',
    L10nKeys.goHome: 'হোমে যান',
    L10nKeys.homeTitle: 'হোম',
    L10nKeys.signInAsGuest: 'গেস্ট হিসেবে সাইন ইন',
    L10nKeys.signIn: 'সাইন ইন',
    L10nKeys.orContinueWith: 'অথবা চালিয়ে যান',
    L10nKeys.continueWithGoogle: 'Google দিয়ে চালিয়ে যান',
  };

  static Map<String, String> forCode(String code) {
    return Map<String, String>.from(code == 'bn' ? bn : en);
  }

  /// Merges API items over local fallbacks so missing keys still resolve.
  static Map<String, String> mergeWithFallback(
    String code,
    Map<String, String> apiItems,
  ) {
    return {...forCode(code), ...apiItems};
  }
}
